clientId = "2386ZY"
userId = "9PYPC9"
#userId = "9934IH"
clientSecret = "29ca93be4466b843bc942ef1e0b9b085"
code = "87cfcdefabe8eff1f0dc02545fc505fff7aaf600"
#accessToken = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMzg2WlkiLCJzdWIiOiI5UFlQQzkiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJybG9jIHJociByYWN0IHJzbGUiLCJleHAiOjE2NDkxNzY2ODEsImlhdCI6MTY0OTE0Nzg4MX0.YpW0m9-P59qRGFScCRTPSI9f01_bwl0RmwKTVfQhuu0"
#refreshToken = "81456fa559761732986b8d93609beb0bac2b269d0dc4155a4c463d3ed838eedd"
mapdbFile = "mapdb.db"
